### ISSUE TITLE
Errors during installation.

### ISSUE THREAD

**Issue by ThomasBardem** [RameenAbdal/StyleFlow#25] opened 2021-01-08 18:20 UTC
I've installed 64 bit version of miniconda, after installation was done I've started up it's Anaconda Prompt, opened the project folder using cd command and pasted conda env create -f environment.yml, it starts to load and then gives me the following error:

`Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - bzip2==1.0.8=h7f98852_4
  - libtiff==4.0.10=h2733197_2
  - libstdcxx-ng==9.1.0=hdf63c60_0
  - mkl_random==1.0.2=py37hd81dba3_0
  - nettle==3.6=he412f7d_0
  - intel-openmp==2019.4=243
  - _libgcc_mutex==0.1=conda_forge
  - ca-certificates==2020.12.8=h06a4308_0
  - _openmp_mutex==4.5=1_llvm
  - libedit==3.1.20181209=hc058e9b_0
  - openh264==2.1.1=h8b12597_0
  - libpng==1.6.37=hbc83047_0
  - freetype==2.9.1=h8a8886c_1
  - gmp==6.2.1=h58526e2_0
  - libffi==3.2.1=hd88cf55_4
  - ffmpeg==4.3.1=h3215721_1
  - libgcc-ng==9.3.0=h5dbcf3e_17
  - av==8.0.2=py37h06622b3_4
  - ncurses==6.1=he6710b0_1
  - sqlite==3.28.0=h7b6447c_0
  - jpeg==9b=h024ee3a_2
  - numpy-base==1.16.4=py37hde5b4d6_0
  - numpy==1.16.4=py37h7e9f1db_0
  - libgfortran-ng==7.3.0=hdf63c60_0
  - xz==5.2.4=h14c3975_4
  - x264==1!152.20180806=h14c3975_0
  - readline==7.0=h7b6447c_5
  - zstd==1.3.7=h0b5b093_0
  - openssl==1.1.1i=h27cfd23_0
  - tk==8.6.8=hbc83047_0
  - llvm-openmp==11.0.0=hfc4b9b4_1
  - libiconv==1.16=h516909a_0
  - lame==3.100=h7f98852_1001
  - scikit-learn==0.22.1=py37hd81dba3_0
  - python==3.7.3=h0371630_0
  - mkl-service==2.3.0=py37he904b0f_0
  - zlib==1.2.11=h7b6447c_3
  - mkl==2019.4=243
  - certifi==2020.12.5=py37h06a4308_0
  - mkl_fft==1.0.12=py37ha843d7b_0
  - gnutls==3.6.13=h85f3911_1`
  
  What could be causing this error? After this failed attempt I tried to move all dependencies to be under - pip: and that gave me errors like `ERROR: Invalid requirement: 'python=3.7.3=h0371630_0'
= is not a valid operator. Did you mean == ?` Then I tried to replace single = with double ==, got errors related to '_libgcc_mutex=0.1=conda_forge' and '_openmp_mutex=4.5=1_llvm',

Just to try one more thing I've removed _ from those and it skipped those (probably because this _ is a part of the filename) and gave me "= is not a valid operator" errors again

I've also tried to leave pip dependency under - dependencies: as I was getting a warning: "Warning: you have pip-installed dependencies in your environment file, but you do not list pip itself as one of your conda dependencies.  Conda may not use the correct pip to install your packages, and they may end up in the wrong place.  Please add an explicit pip dependency.  I'm adding one for you, but still nagging you."

Last error I got after that was `ERROR: No matching distribution found for av==8.0.2==py37h06622b3_4 (from -r \StyleFlow\condaenv.cu4kalq8.requirements.txt (line 1))`

At that point I tried to run install it again with original file (after each try I ran conda env remove -n StyleFlow) and again got the long error with list of dependencies.

**Comment by RameenAbdal** [comment] 2021-01-08 19:13
Duplicate of #16

**Closed by RameenAbdal** 2021-01-08 19:13 UTC
