### ISSUE TITLE
 Cannot open include file: 'tensorflow/core/framework/op.h': No such file or directory

### ISSUE THREAD

**Issue by justinjohn0306** [RameenAbdal/StyleFlow#15] opened 2021-01-07 13:00 UTC
Any ideas on how to fix this error on Windows 10 X64?

![Capture](https://user-images.githubusercontent.com/34035011/103895332-45604700-5116-11eb-913f-a69dc78f885e.PNG)

**Comment by RameenAbdal** [comment] 2021-01-07 16:22
Duplicate of #13

**Closed by RameenAbdal** 2021-01-07 16:22 UTC
